version: '3.7'

services:
  user-service:
    build:
      context: ./task-management/user-service  
    ports:
      - "8081:8081"
    networks:
      - app-network

  task-service:
    build:
      context: ./task-management/task-service 
    ports:
      - "8080:8080"
    depends_on:
      - user-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
